import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "welcome": "Welcome!",

          // base start
          "bitely": "bitely",
          "showMore": "Show More",
          "showLess": "Show Less",
          "cancelAnyTime": "Cancel anytime in the App Store",
          "startMyFree14": "Start My Free 14 Days",
          "display": "Display",
          "darkMode": "Dark Mode",
          "lightMode": "Light Mode",
          "memberShipFeesAreBilled":
              "Membership fees  are billed at the beginning of each period and may take a few days after the billing date to appear on your account.",
          "yourMemberShip": "Your Membershıp",
          "cancelPremium": "Cancel Premium",
          "cancelSubscription": "Cancel Subscription",
          "saveButton": "Save",
          "premiumDetails": "Premium Details",
          "StayingOnTrack": "Staying on Track",
          "welcomeToBitely": "Welcome to Bitely",
          "learnFifteen": "Learn 15 min a day",
          "alreadyHaveAccount": "Already have an account?",
          "reviewYourLearnings": "Review your learnings",
          "improveYourLearning":
              "Improve your learning habits, gain new skills.",
          "addToContentList":
              "Added to your content list. Do you want to read it now?",
          "welcomeToBetaProgram": "Welcome to Bitely Beta Program",
          "verifyAccount": "Verify Account",
          "enterReferralCode": "Enter referral code",
          "enterCodeToStart":
              "Enter code to start improving our user experience",
          "logIn": "Log in",
          "pickAnyOfThe":
              "Pick any of the following options that will take you to your destination.",
          "selectThreeToFive":
              "Select 3 to 5 categories you like to learn about...",
          "timeYouWould": "Time you would like to spend on our app",
          "youCanChange": "You can change your preferences later in settings ",
          "youCanChooseMultiple": "You can choose multiple content language",
          "weAskYourAge":
              "We ask your age range to bring you more interested content",
          "selectYourGender": "Select your gender identity",
          "yourPreferedLearning": "Your preferred learning method",
          "choseOneOf":
              "Choose one of the options so that we can offer you a better recommendation",
          "weCreateYour":
              "We create your personalized plan according to demographic profile, activity level and interests",
          "weAreCreating": "We are creating your account",
          "weWillSendYou":
              "We’ll send you an email with a code to reset your password.",
          "weRecommedThis": "We recommend this book based on your interest",
          "bargainFever": "Bargain Fever",
          "markEllwood": "Mark Ellwood",
          "improveMyself": "Improve myself",
          "learnSomethingNew": "Learn something new",
          "keepMyMind": "Keep my mind active",
          "justForFun": "Just for fun",
          "selfGrowth": "Self-Growth",
          "psychology": "Psychology",
          "marketingSales": "Marketings Sales",
          "politicsSociety": "Politics & Society",
          "healthLifestyleLifestyle": "Health, Lifestyle, Lifestyle",
          "perating": "Perating",
          "mindfulnessHappiness": "Mindfulness & Happiness",
          "sexRelationships": "Sex & Relationships",
          "natureScience": "Nature & Science",
          "economyFinance": "Economy & Finance",
          "CategoriesNames.Business&career": "Business & Carrer",
          "technologyFuture": "Technology & Future",
          "leadershipEntrepreneurship": "Leadership & Entrepreneurship",
          "biographyHistory": "Biography & History",
          "historyCulture": "History & Culture",
          "communicationSkills": "Communication Skills",
          "philosophy": "Philosophy",
          "education": "Education",
          "regular": "Regular",
          "medium": "Medium",
          "advanced": "Advanced",
          "trainMeFive": "Train me 5 minutes a day",
          "trainMeTen": "Train me 10 minutes a day",
          "trainMefifteen": "Train me 15 minutes a day",
          "trainMeTwenty": "Train me 20 minutes a day",
          "english": "English",
          "spanish": "Spanish",
          "turkish": "Turkish",
          "russian": "Russian",
          "female": "Female",
          "male": "Male",
          "nonBinary": "Non-Binary",
          "preferNotToSay": "Prefer Not to Say",
          "eighteenToTwentyFour": "18-24",
          "twentyFiveToThirtyFour": "25-34",
          "thirtyFiveToFourtyFour": "35-44",
          "fourtyFiveToFiftyFour": "45-54",
          "fiftyFivePlus": "55+",
          "read": "Read",
          "listen": "Listen",
          "home": "Home",
          "search": "Search",
          "dailyBites": "DailyBites",
          "library": "Library",
          "profile": "Profile",
          "addToBitelist": "Add to Bitelist",
          "like": "Like",
          "remindMe": "Remind me",
          "share": "Share",
          "seeMore": "See More",
          "seeAll": "See All",
          "bites": "Bites",
          "page": "Page",
          "of": "of",
          "clearAll": "Clear All",
          "whatDoYouWant": "What do you want to read to?",
          "recentSearchesFor": "Recent searches for books, podcasts and videos",
          "noResultFound": "No result found",
          "weAreTryingToGet":
              "We are trying to get to know you before showing your activities",
          "hi": "Hi",
          "or": "Or",
          "goodMorning": "Good Morning",
          "goodNight": "Good Night",
          "editProfile": "Edit Profile",
          "challenges": "Challenges",
          "likes": "Likes",
          "bitelist": "Bitelist",
          "bookmarks": "Bookmarks",
          "finished": "Finished",
          "youHaventStarted": "You haven't started any bites yet",
          "paymentFailed": "Payment failed.",
          "weAreUnable":
              "We are unable to charge your credit card. To keep Premium, update your payment details.",
          "orYouCanStart": "Or you can start with this bites now:",
          "getPremium": "Get Premium",
          "subscribeNowSevenDays": "Subscribe now and try 7 days for free",
          "account": "Account",
          "preferences": "Preferences",
          "notifications": "Notifications",
          "about": "About",
          "aboutBitely": "About  Bitely",
          "giveUsFeedback": "Give Us Feedback",
          "requestContent": "Request Content",
          "contactUs": "Contact Us",
          "privacyPolicy": "Privacy Policy",
          "termsAndConditions": "Terms and Conditions",
          "fullName": "Full Name:",
          "username": "Username:",
          "thinksYouLike": "Thinks You Like",
          "pushNotification": "Push Notification",
          "dailyReminder": "Daily Reminder",
          "personalReminders": "Personal Reminders",
          "thingsYouSaved": "Things You Saved",
          "updateOffers": "Update & Offers",
          "morningLearning": "Morning Learning",
          "youCanChooseMultipleFor":
              "You can choose multiple content languages for the content you want to see.",
          "stayingInTrack": "Staying on Track",
          "getReminders":
              "Get reminders to revise book ideas and get inspired by daily insights.",
          "remeberToHit":
              "Remember to hit your daily reading goal and never lose your streak.",
          "WeWillRecommend":
              "We’ll recommend you new gems based on your interest.",
          "upToDate": "Up to date",
          "weAreSorry": "We are sorry to see you leaving :(",
          "pleaseShareTheReason":
              "Please share the reason why you are leaving.",
          "costRelatedReasons": "Cost-related reasons",
          "iDontUse": "I don't use this app enough",
          "iFoundABetter": "I found a better app",
          "technicalIssues": "Technical issues",
          "notNow": "Not Now",
          "appLanguage": "App Language",
          "language": "Language",
          "contentLanguage": "Content Language",
          "letUsKnow": "Let us know your thoughts!",
          "subject": "Subject",
          "currentPassword": "Current Password",
          "newPassword": "Enter New Password ",
          "newPassword2": "New Password ",
          "reEnterPassword": "Re-enter Password",
          "message": "Message",
          "beginner": "Beginner",
          "noThanks": "No thanks",
          "howYourTrialWorks": "How your trial works",
          "today": "Today",
          "dayTwelve": "Day 12",
          "dayfourteen": "Day 14",
          "unlockFullAccess":
              "Unlock full access to all Bitely Premium features",
          "getReminded": "Get reminded when your trial is about to end",
          "yourAccountIsCharged":
              "Your account is charged, cancel anytime 24 hours before",
          "unlockEndlessPossibilities": "Unlock Endless Possibilities",
          "moreBooks": "More Books, More Features, More Fun",
          "chooseAPlanFor": "Choose a plan for after your 14-day free trial",
          "basic": "Basic",
          "saveDollar": "Save \$24",
          "cancel": "Cancel anytime in the App Store",
          "dollarFourtyNine": '\$49.99',
          "dollarFour": '\$4.99',
          "monthly": 'Monthly',
          "starterPack": 'Starter Pack pay monthly',
          "yearly": 'Yearly',
          "payOnce": 'Pay once,cancel anytime',
          "personalGuidance": "Personal Guidance",
          "endlessContent": "Endless Content",
          "doubleYour": "Double your learning speed",
          "proveYourKnowledge": "Prove Your Knowledge",
          "getPersonalized":
              "Get personalized guidance using artificial intelligence",
          "accessYourBooks": "Access your books with just one button",
          "enjoyYourBooks": "Enjoy your books with no time-limit restrictions",
          "continueYour": "Continue your learning without distractions",
          "adFree": "Ad-Free",

          // base end
          // buttons start
          "buttonSignIn": "Sign in",
          "buttonGetStarted": "Get Started",
          "buttonSignUpFree": "Sign up free",
          "buttonSubmit": "Submit",
          "buttonNext": "Next",
          "buttonCreateAccount": "Create Account",
          "buttonForgotPassword": "Forgot your Password",
          "buttonSend": "Send",
          "buttonStartNow": "Start Now",
          "buttonIWantToPick": "I want to pick one myself",
          "buttonIdLikeToSee": "I'd like to see my activities",
          "buttonDiscover": "Discover",
          "buttonSignOut": "Sign Out",
          "buttonExplore": "Explore",
          "buttonChooseYourPlan": "Choose Your Plan",
          "buttonStartMyFree": "Start My Free 14 Days",
          // buttons end

          // Appbar start
          "appbarReferralCode": "Referral Code",
          "appbarCreateAnAccount": "Create an Account",
          "appbarForgotPassword": "Forgot Password",
          "appbarMainGoal": "Main Goal",
          "appbarCategories": "Categories",
          "appbarDailyTraining": "Daily Training Pace",
          "appbarLanguage": "Language",
          "appbarGender": "Gender",
          "appbarAgeRange": "Age Range",
          "appbarLearningPath": "Learning Path",
          "appbarInterestedInContent": "Interested in This Content ? ",
          "appbarProfile": "Profile",
          "appbarSettings": "Settings",
          "appbarNotification": "Notification",
          "appbarPushNotification": "Push Notification",
          "appbarDeleteAccount": "Delete Account",
          "appbarGiveUsFeedback": "Give Us Feedback",
          "appbarRequestContent": "Request Content",
          "appbarContactUs": "Contact Us",
          "appbarChangePassword": "Change Password",
          "appbarTrainingPace": "Traning Pace",
          // appbar end
          // label start
          "name": "Name",
          "email": "Email",
          "password": "Password ",
          "enterName": "Enter Name",
          "enterEmailAddress": "Enter Email Address",
          "confirmPassword": "Confirm Password",
          "enterVerificationCode": "Enter Verification Code",
          //label end
          // Alert Dialog Start
          "alertAddedTo":
              "Added to your content list. Immediately do you want to read it?",
          "alertMaximum": "Maximum daily Bite limit you have reached",

          // Alert Dialog End
          // validations start
          "eightCharacters": "(8+ characters)",
          // validations end
          // richtext start
          "richByClicking": "By clicking on “Create account” you agree to our ",
          "richTermsOfUse": "Term of Use",
          "richAnd": " and ",
          "richPrivacyPolicy": "Privacy Policy",
          //sadece türkce dil paketi için gecerli hata cıkarabileceğini düşündüğüm için eng kısmını ooluşturup boş string gönderebilirim diye düşündüm.
          "richYouAgree": "",
          "richIfYouDidntReceive": "If you didn't receive a code! ",
          "richResend": "Resend",
          "richIWould":
              "I would prefer to receive marketing messagess from Bitely.",
          "richShareMyRegistration":
              "Share my registration data with Bitely's content providers for marketing purposes.",
          "min": "Min",
          "rememberToHit":
              "Remember to hit your daily reading goal and never lose your streak.",
          // richtext end
          // title start
          "keepReading": "Keep Reading",
          "trendingNow": "Trending Now",
          "collectionsOFTwothousand": "Collections of 2022",
          "forYou": "For You",
          "description": "Description",
          "allBites": "All Bites",
          "insight": "Insight",
          "yourTopCategories": "Your Top Categories",
          "categories": "Categories",
          "recentSearches": "Recent Searches",
          "dailyBitesSpacely": "Daily Bites",
          "activities": "Activities",
          "myBites": "My Bites",
          "completed": "Completed",
          "preview": "Preview",
          "close": "close",
          "buttonDone": "Done",
          "weWillRecommend":
              "We’ll recommend you new gems based on your interest.",
          "buttonDeleteMyAccount": "Delete My Account",

          // title end

          //slider start

          //slider1
          "sliderTitle1": "The Art of War",
          "sliderCategory1": "Leadership & Entrepreneurship",
          "sliderDescription1":
              "Master the art of strategy and achieve victory in any arena",
          //slider2
          "sliderTitle2": "Head Strong",
          "sliderCategory2": "Sport & Lifestyle",
          "sliderDescription2":
              "The Bulletproof Plan to Boost Brainpower, Increase Focus, and Maximize Performance – in Just Two Weeks",
          //slider3
          "sliderTitle3": "Communicate with Master",
          "sliderCategory3": "Communication Skills",
          "sliderDescription3":
              "Unlock the secrets to boost your speaking and writing skills with J.D. Schramm's guide on effective communication",
          //slider4
          "sliderTitle4": "Hear Yourself",
          "sliderCategory4": "Self-growth",
          "sliderDescription4":
              "Find your inner peace and happiness through self-reflection and discovery",
          //slider5
          "sliderTitle5": "Modern Romance",
          "sliderCategory5": "Sex & Relationships",
          "sliderDescription5":
              "Navigate the intricacies of modern-day dating and relationships with Aziz Ansari's witty and thought-provoking commentary on love in the digital age",
          //slider end
          //my bites button
          "imReadyLetsGet": "I'm ready let's get started",
          "letsStart": "Let's start",
          "imDone": "I'm done",
          "newBitePlease": "New bite please",
          //my bites button
        },
        'tr': {
          "welcome": "Hoş geldiniz!",
          "min": "Dk",
          "preview": "Ön İzleme",
          "close": "Kapat",
          "buttonDone": "Bitti",
          "cancelPremium": "primi iptal et",
          "cancelSubscription": "Aboneliği iptal et",
          // base start
          "bitely": "bitely",
          "cancelAnyTime": "App Store'da istediğiniz zaman iptal edin",
          "display": "Ekran",
          "darkMode": "Karanlık mod",
          "lightMode": "ışık modu",
          "startMyFree14": "Ücretsiz 14 Günüme Başla",
          "yourMemberShip": "senin üyeliğin",
          "showMore": "Daha fazla göster",
          "showLess": "Daha az göster",
          "memberShipFeesAreBilled":
              "Üyelik ücretleri her dönemin başında faturalandırılır ve fatura tarihinden sonra hesabınızda görünmesi birkaç gün sürebilir.",
          "saveButton": "Kaydet",
          "premiumDetails": "Fatura Detayları",
          "StayingOnTrack": "Hedefinden Şaşma",
          "welcomeToBitely": "Bitely'e Hoşgeldin",
          "learnFifteen": "15 dakikada bir kitap bitir",
          "alreadyHaveAccount": 'Zaten hesabın var mı?',
          "reviewYourLearnings": "Öğrendiklerini tekrarla",
          "verifyAccount": "Hesabı Doğrula",
          "improveYourLearning":
              "Okuma alışkanlıklarını geliştir, yeni beceriler edin.",
          "addToContentList":
              "İçerik listenize eklendi. Hemen okumak ister misin?",
          "welcomeToBetaProgram": "Bitely’ye Hoşgeldin!",
          "enterReferralCode": "Doğrulama/Davet kodunu girin",
          "enterCodeToStart":
              "İlk kullanıcılarımızdan biri olmana çok az kaldı!",
          "logIn": "Giriş Yap",
          "pickAnyOfThe": "Hedefine en yakın olan seçenekleri seç",
          "selectThreeToFive": "Beğendiğin 3 veya daha fazla kategoriyi seç",
          "timeYouWould": "Uygulamada geçirmek istediğin süreyi seç",
          "youCanChange": "Tercihini daha sonra ayarlardan değiştirebilirsin.",
          "youCanChooseMultiple":
              "Uygulamadaki içerikler için birden fazla dil seçimi yapabilirsiniz.",
          "weAskYourAge":
              "Yaş aralığını sana daha iyi içerikler sunmak için soruyoruz",
          "selectYourGender": "Cinsiyetini seç.",
          "yourPreferedLearning": "Tercih edilen öğrenme yöntemini seç",
          "choseOneOf": "Bu içerik ilgini çekiyorsa beğen butonuna bas",
          "weCreateYour":
              "Kişiselleştirilmiş plan demografik profil, aktiflik seviyesi ve ilgi alanlarına göre oluşturulmaktadır.",
          "weAreCreating": "Hesabını oluşturuyoruz",
          "weWillSendYou":
              "Şifreni sıfırlamak için hesabına bir kod göndereceğiz.",
          "weRecommedThis":
              "İlgi alanlarını baz alarak sana bu kitabı öneriyoruz!",
          "bargainFever": "Bargain Fever",
          "markEllwood": "Mark Ellwood",
          "improveMyself": "Kişisel gelişim",
          "learnSomethingNew": "Yeni şeyler öğrenmek",
          "keepMyMind": "Zihin egzersizleri yapmak",
          "justForFun": "Sadece eğlence",
          "selfGrowth": "Kişisel Gelişim",
          "psychology": "Psikoloji",
          "politicsSociety": "Siyaset",
          "healthLifestyleLifestyle": "Sağlık & Yaşam",
          "perating": "Aile ve Çocuk",
          "mindfulnessHappiness": "Farkındalık",
          "sexRelationships": "Satış & Pazarlama",
          "natureScience": "Doğa & Bilim",
          "economyFinance": "Ekonomi & Finans",
          "CategoriesNames.Business&career": "İş & Kariyer",
          "technologyFuture": "Gelecek & Teknoloji",
          "leadershipEntrepreneurship": "Girişimcilik & Liderlik",
          "biographyHistory": "Biyografi & Anı Yazısı",
          "historyCulture": "Kültür & Tarih",
          "communicationSkills": "İletişim",
          "philosophy": "Felsefe",
          "education": "Eğitim",
          "marketingSales": "Satış & Pazarlama",
          "regular": "Standart",
          "medium": "Orta Seviye",
          "advanced": "İleri Seviye",
          "trainMeFive": "Günde 5 dakika",
          "trainMeTen": "Günde 10 dakika",
          "trainMefifteen": "Günde 15 dakika",
          "trainMeTwenty": "Günde 20 dakika",
          "english": "İngilizce",
          "spanish": "İspanyolca",
          "turkish": "Türkçe",
          "russian": "Rusça",
          "female": "Kadın",
          "male": "Erkek",
          "nonBinary": "Non-Binary",
          "preferNotToSay": "Belirtmek İstemiyorum",
          "eighteenToTwentyFour": "18-24",
          "twentyFiveToThirtyFour": "25-34",
          "thirtyFiveToFourtyFour": "35-44",
          "fourtyFiveToFiftyFour": "45-54",
          "fiftyFivePlus": "55+",
          "read": "Okumak",
          "listen": "Dinlemek",
          "home": "Ana Sayfa",
          "search": "Arama",
          "dailyBites": "Bite",
          "library": "Kitaplık",
          "profile": "Profil",
          "addToBitelist": "Bitelist’e Ekle",
          "like": "Beğen",
          "remindMe": "Hatırlat",
          "share": "Paylaş",
          "seeMore": "devamı",
          "seeAll": "Tümü",
          "bites": "Bites",
          "page": "Sayfa",
          "of": "/",
          "clearAll": "Temizle",
          "whatDoYouWant": "Ne okumak istersin?",
          "recentSearchesFor": "Kitap, podcast ve videolar için son aramalar",
          "noResultFound": "Sonuç bulunamadı",
          "weAreTryingToGet":
              "İstatistik sayfanı düzenlemeden önce seni tanımaya çalışıyoruz",
          "hi": "Merhaba",
          "or": "Veya",
          "goodMorning": "Günaydın",
          "goodNight": "İyi Geceler",
          "editProfile": "Profili Düzenle",
          "challenges": "Challenge",
          "likes": "Beğenilenler",
          "bitelist": "Bite Listesi",
          "bookmarks": "Kaydedilenler",
          "finished": "Biten",
          "youHaventStarted": "Henüz bir bite tamamlamadın.",
          "paymentFailed": "Ödeme başarısız.",
          "weAreUnable":
              "İşlem gerçekleştirilemedi. Premium üyeliğinizin devam etmesi için ödeme bilgilerinizi güncelleyin.",
          "orYouCanStart": "Veya bu kitaplar ile başlayabilirsin:",
          "getPremium": "Premium Satın Al",
          "subscribeNowSevenDays": "Şimdi planını seç ve 7 gün ücretsiz dene!",
          "account": "Hesap",
          "preferences": "Tercihler",
          "notifications": "Bildirimler",
          "about": "hakkında",
          "aboutBitely": "Bitely hakkında",
          "giveUsFeedback": "Geri bildirim",
          "requestContent": "İçerik Talebi",
          "contactUs": "Bize ulaş",
          "privacyPolicy": "Gizlilik sözleşmesi",
          "termsAndConditions": "Kullanım şartları",
          "fullName": "İsim Soyisim:",
          "username": "Kullanıcı Adı:",
          "thinksYouLike": "Beğendiklerin",
          "pushNotification": "Anlık Bildirimler",
          "dailyReminder": "Günlük Hatırlatıcılar",
          "personalReminders": "Kişisel Hatırlatıcılar",
          "thingsYouSaved": "Kaydedilenler",
          "updateOffers": "Güncellemeler & Teklifler",
          "morningLearning": "Güne Yeni Bir Bilgiyle Başla",
          "youCanChooseMultipleFor": "Birden fazla dil seçimi yapabilirsiniz",
          "stayingInTrack": "Hedefinden Şaşma",
          "getReminders":
              "Günlük anahtar fikirlerle en sevdiğin kitapları tekrar et.",
          "remeberToHit": "Günlük okuma hedefini tamamlayarak serini koru.",
          "WeWillRecommend":
              "İlgi alanlarına göre sana tavsiye edeceğimiz yeni içerikleri kaçırma.",

          "rememberToHit": "Günlük okuma hedefini tamamlayarak serini koru.",

          "upToDate": "Yeni İçeriklerden Haberdar Ol",
          "weAreSorry": "Hesabını silmek istediğine emin misin?",
          "pleaseShareTheReason": "Lütfen ayrılma sebebini paylaş.",
          "costRelatedReasons": "Çok pahalı/artık ödeyemiyorum",
          "iDontUse": "Uygulamayı yeterince kullanmıyorum",
          "iFoundABetter": "Daha iyi bir uygulama buldum",
          "technicalIssues": "Teknik sorunlar",
          "notNow": "Henüz Değil",
          "appLanguage": "Uygulama Dili",
          "language": "Dil",
          "contentLanguage": "İçerik Dili",
          "letUsKnow": "Düşüncelerinizi bizimle paylaşın!",
          "subject": "Konu",
          "currentPassword": "Güncel Şifre",
          "newPassword": "Yeni Şifre",
          "newPassword2": "Yeni Şifre",
          "reEnterPassword": "Yeni Şifre (tekrar)",
          "message": "Mesaj",
          "beginner": "Başlangıç",
          "noThanks": "Hayır, Teşekkürler",
          "howYourTrialWorks": "Deneme sürecin nasıl işleyecek?",
          "today": "Bugün",
          "dayTwelve": "12 Gün",
          "dayfourteen": "14 Gün",
          "unlockFullAccess":
              "Bitely’nin tüm premium özelliklerine erişim sağla.",
          "getReminded": "Deneme sürecin bitmeden sana haber verilir.",
          "yourAccountIsCharged":
              "Ödeme alınır. 24 saat öncesine kadar iptal edebilirsin.",
          "unlockEndlessPossibilities":
              "Tüm İçeriklere Sınırsız Erişim Sağlayın",
          "moreBooks": "Binlerce kitap, Yepyeni özellikler, Sınırsız eğlence",
          "chooseAPlanFor": "14 günlük deneme sürecinin ardından geçeceğin",
          "basic": "Standart",
          "saveDollar": "\$24 Tasarruf ",
          "cancel":
              "(AppStore or Google Play) sayfasından istediğiniz zaman iptal edebilirsiniz.",
          "dollarFourtyNine": '\$49.99',
          "dollarFour": '\$4.99',
          "monthly": 'Aylık',
          "starterPack": 'Standart Paket, aylık ödeme',
          "yearly": 'Yıllık',
          "payOnce": 'Bir kere öde istediğin zaman iptal et',
          "personalGuidance": "Kişisel Rehber",
          "endlessContent": "Sınırsız Kitap",
          "doubleYour": "Öğrenme hızınızı ikiye katlayın",
          "proveYourKnowledge": "Bilgini Kanıtla",
          "getPersonalized":
              "Yapay zeka ile kişiselleştirilmiş içerik kılavuzu",
          "accessYourBooks": "İstediğin kitaba istediğin anda ulaş",
          "enjoyYourBooks": "Zaman sınırına takılmadan istediğin kadar öğren",
          "continueYour": "Dikkatin dağılmadan kesintisiz öğren",
          "adFree": "Reklam Yok",
          "weWillRecommend":
              "İlgi alanlarına göre sana tavsiye edeceğimiz yeni içerikleri kaçırma.",
          "buttonDeleteMyAccount": "Hesabımı Sil",
          // base end
          // buttons start
          "buttonSignIn": "Giriş Yap",
          "buttonGetStarted": "Başla",
          "buttonSignUpFree": "E-posta ile kayıt ol",
          "buttonSubmit": "Gönder",
          "buttonNext": "İleri",
          "buttonCreateAccount": "Hesap Oluştur",
          "buttonForgotPassword": "Şifreni mi unuttun?",
          "buttonSend": "Gönder",
          "buttonStartNow": "Hemen Başla",
          "buttonIWantToPick": "Kendim seçmek istiyorum",
          "buttonIdLikeToSee": "İstatistiklerini Gör",
          "buttonDiscover": "Keşfet",
          "buttonSignOut": "Hesabı Sil",
          "buttonExplore": "Keşfet",
          "buttonChooseYourPlan": "Plan Seç",
          "buttonStartMyFree": "Deneme Sürecine Başla",
          // buttons end

          // Appbar start
          "appbarReferralCode": "Davet Kodu",
          "appbarCreateAnAccount": "Hesap Oluştur",
          "appbarForgotPassword": "Şifreni mi Unuttun",
          "appbarMainGoal": "Ana Hedef",
          "appbarCategories": "Kategori",
          "appbarLanguage": "İçerik Dili",
          "appbarGender": "Cinsiyet",
          "appbarAgeRange": "Yaş Aralığı",
          "appbarLearningPath": "Öğrenme Yöntemi",
          "appbarInterestedInContent": "İlgini Çekiyor Mu?",
          "appbarProfile": "Profil",
          "appbarSettings": "Ayarlar",
          "appbarNotification": "Bildirimler",
          "appbarPushNotification": "Anlık Bildirimler",
          "appbarDeleteAccount": "Hesabımı Sil",
          "appbarGiveUsFeedback": "Geri bildirim",
          "appbarRequestContent": "İçerik Talebi",
          "appbarContactUs": "Bize Ulaş",
          "appbarDailyTraining": "Günlük Tempo",
          "appbarChangePassword": "Şifre Değiştir",
          "appbarTrainingPace":
              "Günlük Tempo", // tasarımdan kaldırılmış olabilir
          // appbar end
          // label start
          "name": "İsim",
          "email": "E-posta",
          "password": "Şifre",
          "enterName": "Name Girin",
          "enterEmailAddress": "E-posta Adresini Girin",
          "confirmPassword": "Şifreyi Doğrula",
          "enterVerificationCode": "Doğrulama kodunu girin",
          //label end
          "alertAddedTo": "Listene eklendi. Hemen okumamı ister misin?",
          "alertMaximum": "Günlük maksimum sınırı aştınız.",
          // validations start
          "eightCharacters": "(8+ karakter)",
          // validations end
          // richtext start
          "richByClicking": "Hesap oluştura tıklayarak ",
          "richTermsOfUse": "Gizlilik Politikası ",
          "richAnd": "ve",
          "richPrivacyPolicy": "Kullanım Şartlarını",
          //sadece türkce dil paketi için gecerli
          "richYouAgree": "kabul etmiş olursunuz",
          "richIfYouDidntReceive": "Eğer hesabınıza kod gelmediyse!",
          "richResend": "Tekrar Gönder",
          "richIWould":
              "Bitely, tarafıma ürün, hizmet ve fırsatlarla ilgili reklam ve promosyon iletileri göndersin.",
          "richShareMyRegistration":
              "Kişisel verilerimin pazarlama faaliyetlerinde kullanılmasını kabul ediyorum",

          // richtext end
          // title start
          "keepReading": "Okumaya devam et",
          "trendingNow": "Şu anda popüler",
          "collectionsOFTwothousand": "2022 Koleksiyonları",
          "forYou": "Senin İçin",
          "description": "Açıklama",
          "allBites": "Bite",
          "insight": "Anahtar Fikir",
          "yourTopCategories": "Favori Kategorilerin",
          "categories": "Kategoriler",
          "recentSearches": "Son Aramalar",
          "dailyBitesSpacely": "Günlük Bitelar",
          "activities": "Aktivite",
          "myBites": "Bitelarım",
          "completed": "Tamamlananlar",
          // title end

          //slider start
          //slider1
          "sliderTitle1": "The Art of War",
          "sliderCategory1": "Liderlik & Girişimcilik",
          "sliderDescription1":
              "Strateji sanatında ustalaşın ve hayatınızın her alanında zafere ulaşın",
          //slider2
          "sliderTitle2": "Head Strong",
          "sliderCategory2": "Yaşam,Sağlık ve Spor-Health",
          "sliderDescription2":
              "Sadece İki Haftada Beyin Gücünüzü ve Odağınızı Artırmak, Performansı En Üst Düzeye Çıkarmak için Kurşun Geçirmez Plan!",
          //slider3
          "sliderTitle3": "Communicate with Master",
          "sliderCategory3": "İletişim Becerileri",
          "sliderDescription3":
              "J.D. Schramm'ın etkili iletişim kılavuzuyla konuşma ve yazım becerilerinizi bir üst seviyeye çıkarmanın sırlarını keşfedin!",
          //slider4
          "sliderTitle4": "Hear Yourself",
          "sliderCategory4": "Kişisel Gelişim",
          "sliderDescription4":
              "İç dünyanızda bir keşif yolculuğuna çıkarak huzura ve mutluluğa ulaşın",
          //slider5
          "sliderTitle5": "Modern Romance",
          "sliderCategory5": "Cinsellik ve İliskiler",
          "sliderDescription5":
              "Aziz Ansari'nin dijital çağda aşk üzerine esprili ve düşündürücü yorumuyla günümüz flört ve ilişki dünyasında bir keşfe çıkın",
          //slider end
          //my bites button
          "imReadyLetsGet": "ben hazırım hadi başlayalım",
          "letsStart": "Hadi başlayalım",
          "imDone": "bitirdim",
          "newBitePlease": "yeni Bite lütfen",
          //my bites button
        },
      };
}
